services:
  music_nginx:
    image: nginx:latest
    container_name: music_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=music.localhost
      - NGINX_PORT=80
    networks:
      - internal

  music_app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: music_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - internal
    command:
      - "php-fpm"

networks:
  internal:
    driver: bridge